name: process_plus
version: 2.0.0
description: Helpers classes and added functionality for `package:process`.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/process_plus
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  pool: ^1.0.0
  process: ^3.0.0
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0